

$bootstrap = "../../../.local/share/initio/bootstrap.sh"

Vagrant.configure("2") do |config|

    # Run bootstrap script
    config.vm.provision "shell", path: $bootstrap, env: {"INITIO_TEST" => "true"}, privileged: false
    
    # Install git-hook for dev/test cycle
    config.vm.provision "file", source: "./git-hooks/post-receive", destination: "~/.git/hooks/post-receive"

    # Shared dir, if provider supports it
    config.vm.synced_folder "../../../", "/vagrant", type: "rsync" #, disabled: true

    #
    # Provider
    #
    config.vm.provider "virtualbox" do |virtualbox|
        virtualbox.gui = 1
    end

    #
    # MacOS
    #
    config.vm.define "macos", autostart: false do |macos|        
        macos.vm.box = "emil-appunite/macos10.13-xcode9.1"
        macos.vm.box_version = "1.0.0"
    end

    #
    # Linux
    #
    config.vm.define "debian", autostart: false do |debian|
        debian.vm.autostart = false
    end
end