---

#
# Provisioner finalizations
#

- name: Remove git dir from boostrap checkout
  file:
    path: ~/.git
    state: absent
  when: lookup('env','INITIO_TEST') is not defined or lookup('env','INITIO_TEST') != "true"


#
# MacOS
#

- name: MacOS postflights
  block:
    - name: Enable GateKeeper
      command: spctl --master-enable
    - name: Enable KextConsent
      command: spctl kext-consent enable
  become: yes
  when: distro.macos


#
# Linux
#
