---
#
# Provision components of infrastructure
#
- hosts: all
  strategy: linear
  vars:
    endpoints:
      - laptop
      - workstation
      - headnode
      - fileserver
      - compute
  vars_files:
    - default.config.yml

#
# Prompt for endpoint and config
#
# TODO: https://github.com/ansible/ansible/issues/32723
  vars_prompt:
    - name: "endpoint"
      prompt: |

        Endpoint type?
        ---------------
        laptop
        workstation
        headnode
        fileserver
        compute

      default: "laptop"
      private: no

  pre_tasks:
    - name: "Preflight checks"
      include_tasks: playbooks/preflight.yml


#
# Common provisioning
#
  roles:
    - common
    - zsh
    - gnupg
    - dotfiles
    - secrets
    - mackup
    - fonts
    - security


#
# Endpoint specifics
#
# hack: workaround until ansible fixes include_role name eval
# see: https://github.com/ansible/ansible/pull/33386
  tasks:
    - include_role: name=laptop
      when: endpoint == "laptop"


#
# Cleanup
#
  post_tasks:
    - name: "Postflight tasks"
      include_tasks: playbooks/postflight.yml

