---

#
# Dotfile manager and frameworks
#

- name: Clone yadm
  git: >
    repo={{initio_yadm}}
    dest="{{xdg.local}}/lib/yadm"

- name: Clone Zim
  git: >
    repo={{initio_zim}}
    dest="{{xdg.config}}/zsh/zim"

- name: Link yadm bin
  file:
    src: "{{yadm.bin}}"
    dest: "{{xdg.local}}/bin/yadm"
    state: link
  tags: [symlink]


#
# Apply dotfiles
#

- stat:
    path: "{{initio.tmp}}/.git/config"
  register: cached_repo

- stat:
    path: "{{yadm.dir}}/repo.git/config"
  register: yadm_repo

- name: Load initio from repo
  shell: |
    {{yadm.bin}} -Y {{yadm.dir}} clone "{{initio_repo}}"
    {{yadm.bin}} -Y {{yadm.dir}} reset --hard origin/{{initio_branch}}
    {{yadm.bin}} -Y {{yadm.dir}} checkout {{initio_branch}}
  when: not yadm_repo.stat.exists and not cached_repo.stat.exists

- name: Load initio from local cache
  block:
    - shell: "{{yadm.bin}} -Y {{yadm.dir}} clone {{initio.tmp}}"
    - shell: |
        cd ~
        {{yadm.bin}} -Y {{yadm.dir}} remote remove origin
        {{yadm.bin}} -Y {{yadm.dir}} remote add origin {{initio_repo}}
  when: not yadm_repo.stat.exists and cached_repo.stat.exists

- shell: "which zsh"
  register: zsh_path

- name: Zmanage update
  shell: "source {{user_home}}/.zshrc && zmanage update"
  args:
     executable: "{{zsh_path.stdout}}"
  ignore_errors: yes

#
# Symlink adhoc dotfiles
#

- name: Symlink individual dotfiles
  include_tasks: symlinks.yml
  tags: [symlink]
  