---

- name: Setting up fonts FONT_HOME
  file:
    path: "{{xdg.local}}/share/fonts"
    recurse: yes
    state: directory


#
# MacOS
#
- name: Install Source Code Pro
  block:
  - homebrew_tap:
      name: homebrew/cask-fonts
  - homebrew_cask:
      name: font-source-code-pro
      state: present
  when: distro.macos
 

#
# Linux
#
- name: Install Source Code Pro
  block:
    - file:
        path: "{{xdg.local}}/share/fonts/adobe-fonts/source-code-pro"
        recurse: yes
        state: directory
    - git: >
        repo='https://github.com/adobe-fonts/source-code-pro.git'
        dest={{xdg.local}}/share/fonts/adobe-fonts/source-code-pro
        depth=1
        version=release
    - name: Update font cache
      shell: >
        fc-cache -f -v "$FONT_HOME/adobe-fonts/source-code-pro"
  when: distro.linux

